[package]
name = "docstrify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
crossbeam = "0.8.2"
rayon = "1.5.3"
regex = "1.6.0"
ripgrep = "13.0.0"
termcolor = "1.1.3"
thiserror = "1.0.37"
