[package]
name = "STKLR"
version = "0.0.1"
edition = "2021"
authors = ["alphastrata <alphastrata@gmail.com>"]
license = "MIT"
description = "STKLR, pronounced 'stickler' is a cli tool to automatically link functions, enums, structs, traits etc in rust-doc docstrings."
homepage = "https://github.com/alphastrata"
repository = "https://github.com/alphastrata/stklr.git"
readme = "README.md"
keywords = ["docs"]
publish = false

[dependencies]
anyhow = "1.0.65"
crossbeam = "0.8.2"
glob = "0.3.0"
lazy_static = "1.4.0"
quote = "1.0.21"
rayon = "1.5.3"
regex = "1.6.0"
ripgrep = "13.0.0"
syn = "1.0.101"
termcolor = "1.1.3"
thiserror = "1.0.37"
